### ISSUE TITLE
Auto stop not working

### ISSUE THREAD

**Issue by gmclelland** [andygott/Really-Simple-Slideshow#19] opened 2012-06-21 22:34 UTC
Hello, first of all I would like to thank you for providing this wonderful script.

One issue I am running into is that the autostop: true doesn't seem to work.  When I click the next or prev links, I was expecting it to stop the slideshow from playing.

Here is my js snippet I'm using

``` javascript
$(document).ready(function () {

  $('.rs-slideshow').rsfSlideshow({
    controls: {
      previousSlide: {
        auto: true,
        autostop: true
      },
      nextSlide: {
        auto: true,
        autostop: true
      }
    }
  });

});
```

**Comment by alypax** [comment] 2012-10-25 14:21
Did you ever figure this out??

**Comment by gmclelland** [comment] 2012-10-25 15:09
Well, not really.  I ended up pausing the slideshow when the slideshow or controls is hovered.  When the user hovers off  it will resume.

**Comment by andygott** [comment] 2012-10-25 16:43
Closing as a duplicate of #15 – Now fixed, see comment on that issue for an update.

**Closed as completed by andygott** 2012-10-25 16:43 UTC
